package domain

import "strings"

// ChapterPlan is a chapter writing plan, generated autonomously by the Writer.
// Scene splitting is no longer mandatory; the agent decides how to organise the content.
type ChapterPlan struct {
	Chapter    int             `json:"chapter"`
	Title      string          `json:"title"`
	Goal       string          `json:"goal"`
	Conflict   string          `json:"conflict"`
	Hook       string          `json:"hook"`
	EmotionArc string          `json:"emotion_arc,omitempty"`
	Notes      string          `json:"notes,omitempty"` // Free-form agent notes
	Contract   ChapterContract `json:"contract,omitempty"`
}

// ChapterContract is the chapter acceptance contract shared by the Writer and the Editor.
// It defines the advances the chapter must deliver, the moves that must not happen, and the
// points the review should focus on.
type ChapterContract struct {
	RequiredBeats    []string `json:"required_beats,omitempty"`    // Advances that must land in this chapter
	ForbiddenMoves   []string `json:"forbidden_moves,omitempty"`   // Advances explicitly forbidden in this chapter
	ContinuityChecks []string `json:"continuity_checks,omitempty"` // Continuity points needing a dedicated check here
	EvaluationFocus  []string `json:"evaluation_focus,omitempty"`  // Points the Editor must check closely
	EmotionTarget    string   `json:"emotion_target,omitempty"`    // Optional: the emotion readers should mainly feel here
	PayoffPoints     []string `json:"payoff_points,omitempty"`     // Optional: plot/payoff points a key chapter should honour
	HookGoal         string   `json:"hook_goal,omitempty"`         // Optional: the read-on urge the closing hook should drive
}

// ChapterSummary is the chapter summary, used by later chapters' context windows.
type ChapterSummary struct {
	Chapter    int      `json:"chapter"`
	Title      string   `json:"title"`
	Summary    string   `json:"summary"`
	Characters []string `json:"characters"`
	KeyEvents  []string `json:"key_events"`
}

// ArcSummary is the arc-level summary, generated by the Editor when an arc ends.
type ArcSummary struct {
	Volume    int      `json:"volume"`
	Arc       int      `json:"arc"`
	Title     string   `json:"title"`
	Summary   string   `json:"summary"`
	KeyEvents []string `json:"key_events"`
}

// VolumeSummary is the volume-level summary, generated when a volume ends.
type VolumeSummary struct {
	Volume    int      `json:"volume"`
	Title     string   `json:"title"`
	Summary   string   `json:"summary"`
	KeyEvents []string `json:"key_events"`
}

// CharacterSnapshot is a character state snapshot, recorded at arc boundaries.
type CharacterSnapshot struct {
	Volume     int    `json:"volume"`
	Arc        int    `json:"arc"`
	Name       string `json:"name"`
	Status     string `json:"status"`
	Power      string `json:"power,omitempty"`
	Motivation string `json:"motivation"`
	Relations  string `json:"relations,omitempty"`
}

// OutlineFeedback is the Writer's feedback on the outline, optional at chapter commit.
type OutlineFeedback struct {
	Deviation  string `json:"deviation"`  // Deviation description
	Suggestion string `json:"suggestion"` // Adjustment suggestion
}

// WritingStyleRules are writing rules distilled from the chapters already written, generated by
// the Editor at arc boundaries.
// They replace verbatim excerpts (style_anchors / voice_samples), substituting rules for
// copying source text around.
type WritingStyleRules struct {
	Volume    int              `json:"volume"`
	Arc       int              `json:"arc"`
	Prose     []string         `json:"prose"`      // 3-5 narration style rules, each <=50 chars
	Dialogue  []CharacterVoice `json:"dialogue"`   // Per-character dialogue style rules
	Taboos    []string         `json:"taboos"`     // Taboo list
	UpdatedAt string           `json:"updated_at"` // ISO8601 timestamp
}

// CharacterVoice holds one character's dialogue style rules.
type CharacterVoice struct {
	Name  string   `json:"name"`
	Rules []string `json:"rules"` // 2-3 language-feature rules, each <=30 chars
}

// RelatedChapter is a related chapter recommended for re-reading.
type RelatedChapter struct {
	Chapter int    `json:"chapter"`
	Reason  string `json:"reason"`
}

// RecallItem is long-term information selectively recalled for the current task.
// It does not replace the formal artefacts; it only feeds a small amount of genuinely relevant
// history back to the model for this round.
type RecallItem struct {
	Kind    string `json:"kind"`
	Key     string `json:"key,omitempty"`
	Chapter int    `json:"chapter,omitempty"`
	Reason  string `json:"reason,omitempty"`
	Summary string `json:"summary,omitempty"`
}

// CommitResult is the structured return value of the commit_chapter tool.
// It contains fact fields only; "what to do next" is generated by the Reminder channel from the
// current Progress.
type CommitResult struct {
	Chapter        int              `json:"chapter"`
	Committed      bool             `json:"committed"`
	WordCount      int              `json:"word_count"`
	NextChapter    int              `json:"next_chapter"`
	ReviewRequired bool             `json:"review_required"`
	ReviewReason   string           `json:"review_reason,omitempty"`
	HookType       string           `json:"hook_type,omitempty"`
	DominantStrand string           `json:"dominant_strand,omitempty"`
	Feedback       *OutlineFeedback `json:"feedback,omitempty"`
	// Layered long-form signals
	ArcEnd         bool `json:"arc_end,omitempty"`
	VolumeEnd      bool `json:"volume_end,omitempty"`
	Volume         int  `json:"volume,omitempty"`
	Arc            int  `json:"arc,omitempty"`
	NeedsExpansion bool `json:"needs_expansion,omitempty"`  // Next arc is a skeleton and needs chapter expansion
	NeedsNewVolume bool `json:"needs_new_volume,omitempty"` // Architect must create the next volume
	NextVolume     int  `json:"next_volume,omitempty"`      // Next volume/arc index
	NextArc        int  `json:"next_arc,omitempty"`         // Next arc index
	// Completion fact: whether the whole book finished after this commit.
	BookComplete bool `json:"book_complete,omitempty"`
	// Snapshot of the current Progress.Flow (writing / reviewing / rewriting / polishing).
	Flow string `json:"flow,omitempty"`
}

// HasDirective reports whether this chapter plan actually says what to write.
//
// An empty plan is equivalent to no plan at all: rework that lists only symptoms without a
// direction leaves the Writer with nothing but "rewrite chapter N" — the Editor was observed
// rating that as the most severe problem in the queue.
func (p ChapterPlan) HasDirective() bool {
	return strings.TrimSpace(p.Goal) != "" ||
		len(p.Contract.RequiredBeats) > 0 ||
		len(p.Contract.PayoffPoints) > 0 ||
		len(p.Contract.ContinuityChecks) > 0
}
